require "user.plugins.packer"

require "user.plugins.bufferline"
require "user.plugins.cmp"
require "user.plugins.neotest"
require "user.plugins.neo-tree"
require "user.plugins.telescope"
require "user.plugins.toggleterm"
require "user.plugins.treesitter"
require "user.plugins.lsp"
